################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header: 
  image: 
    altText: "Payments Exchange: RTP™"
    link: /assets/images/Fiserv_Logo.jpg
  productName: PaymentsExchangeRTP
  productionDescription: "Payments Exchange: RTP is a flexible, web-based solution that streamlines RTP message and response handling for complete end-to-end RTP payment processing. This innovative tool gives your institution the ability to access the RTP network and ensures operational efficiency and security."
  whoIsItFor: "Payments Exchange: RTP is for financial institutions who want to engage in direct RTP participation. You can connect to TCH’s RTP network and track your payments easily through a web-enabled UI."
steps: 
  buildSteps: 
    - 
      description: "Get your application up and running with our proprietary integration tools and developer keys. \n"
      link: ~
      title: Build
  deploySteps: 
    - 
      description: "Deploy your applications in our testing environment for quality assurance testing.  Once ready promote your application to our production environment. \n"
      link: ~
      title: Deploy
  learnSteps: 
    - 
      description: "Follow our documentation and easy to use examples to build your own mobile or web integrated online applications. \n"
      link: ~
      title: Learn
  validateSteps: 
    - 
      description: "Interact with our live api interface for real time responses to the developed application. \n"
      link: ~
      title: "API Explorer"
